# Generated by Django 3.0.3 on 2021-02-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210219_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mark_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.PositiveIntegerField(),
        ),
    ]
