# Generated by Django 3.0.3 on 2021-02-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_by',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
